---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/jeroen-vankelecom/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Configuration/dotfiles
dotfiles_files:
  - .zshrc
  - .aliases
  - .autocompletion
  - .functions
  - .gitignore
  - .gitconfig
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - asciinema
  - awscli
  - bash-completion
  - docker-completion
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - mysql
  - node
  - postgresql
  - python
  - python@2
  - sqlite
  - nmap
  - ssh-copy-id
  - cowsay
  - openssl
  - pv
  - s3cmd
  - telnet
  - terraform
  - tmux
  - vim
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - sambadevi/powerlevel9k

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: true
homebrew_group: "504" # brew group

homebrew_cask_apps:
  - aws-vault
  - basictex
  - cloudmounter
  - dash
  - docker
  - drawio
  - dropbox
  - evernote
  - firefox
  - font-hack-nerd-font
  - goland
  - google-backup-and-sync
  - google-chat
  - google-chrome
  - google-hangouts
  - iterm2
  - keybase
  - licecap
  - postman
  - powerlevel9k
  - sequel-pro
  - spectacle
  - spotify
  - suspicious-package
  - texmaker
  - the-unarchiver
  - tunnelblick
  - { name: virtualbox, install_options:"debug,appdir=/Applications" } # you might need to allow software from Oracle America Inc (System Preferences > Security > General)
  - visual-studio-code
  - vlc
  - whatsapp
  # improve Mac Finder Quick Look functionalities
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - qlprettypatch
  - quicklook-csv
  - webpquicklook

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: [{ id: 937984704, name: "Amphetamine" }]
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
